[package]
name = "hotkeys_for_lzr_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
captrs = "0.3.1"
hotkey = "0.3.1"
rand = "0.8.5"
rsautogui = "0.1.5"
screenshots = "0.4.6"
winit = "0.27.5"
